services:
  - type: web
    name: lieyou-bot-webhook
    env: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false           # 控制台中填写
      - key: ADMIN_USER_ID
        value: "123456789"    # 替换为你的 Telegram 数字 ID
      - key: DATABASE_URL
        sync: false           # 控制台中填写（Neon URL，必须 ?sslmode=require）
      - key: DB_POOL_MIN
        value: "0"
      - key: DB_POOL_MAX
        value: "8"
      - key: SECRET_TOKEN
        sync: false           # 控制台中填写（随机长字符串）
      - key: WEBHOOK_PATH
        value: "/webhook/abc123xyz"   # 可在控制台更改，或留空用默认
    # 可选健康检查路径（使用 PTB 内置服务器无法自定义路由，故不设置）
    # healthCheckPath: /health

jobs:
  - type: job
    name: lieyou-migrate
    env: python
    plan: free
    autoDeploy: false
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python migrate.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        value: "123456789"
      - key: DATABASE_URL
        sync: false
      - key: DB_POOL_MIN
        value: "0"
      - key: DB_POOL_MAX
        value: "8"
